config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :matches, :users

  devise_scope :user do
    get "new_user_session", to: "devise/sessions#new" 
    get '/logout',  :to => "devise/sessions#destroy"
  end

  root 'matches#index'
end

app/models/match.rb
class Match < ActiveRecord::Base

	validates_presence_of :winner_id, :loser_id, :score, :played_at

	validates_with MatchValidator
	
	has_and_belongs_to_many :users

end

app/models/user.rb
# This repesents player......
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :matches

	validates_presence_of :firstname, :lastname, :email
	validates_uniqueness_of :email

  has_attached_file :avatar, styles: { medium: "100x100>", thumb: "25x25>" },
  	default_url: "/images/:style/missing.png"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  
  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:firstname, :lastname, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:firstname, :lastname, :email, :password, :current_password, :avatar) }
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  before_action :redirect, only: [:new, :create]
  
  expose(:match)

	def index
    @matches = Match.all
  end

  def new
    @match = Match.new(played_at: Time.now.localtime)
  end

  def create
    @match = Match.new(match_params)

    @match.surprise_victory = surprise?(@match) if @match != nil

    if @match.save
      join_match_with_users(@match)
      redirect_to root_path, notice: 'match was successfully created.'
    else
      render action: 'new'
    end
  end

  private

  def match_params
    params.require(:match).permit(:winner_id, :loser_id, :score, :played_at)
  end

  def redirect
    redirect_to(new_user_session_path) unless user_signed_in? && current_user.admin
  end

  def join_match_with_users(match)
    match.users << User.where(id: [match.winner_id, match.loser_id])
  end

  def surprise?(match)
    UsersService.new.surprise_victory?(@match.winner_id, @match.loser_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :users_service

  expose(:user)
  expose(:users)

  def index
    @users = User.all
  end

  def show
    @user = current_user

    respond_to do |format|
      format.html
      format.xml { render :xml => @user }
    end
  end

  private

  def users_service
  	@users_service = UsersService.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper

	def winner_avatar_url(match, size)
		winner(match).avatar.url(size)
	end

	def loser_avatar_url(match, size)
		loser(match).avatar.url(size)
	end

	def winner(match)
		match.users.find(match.winner_id)
	end

	def loser(match)
		match.users.find(match.loser_id)
	end

	def result(match)
		"10 : #{match.score}"
	end

	def date(match)
		match.played_at.strftime("%d/%m/%Y")
	end

	def time(match)
		match.played_at.strftime("%H:%M")
	end

	def winner_fullname(match)
		fullname(winner(match))
	end

	def loser_fullname(match)
		fullname(loser(match))
	end
end

app/helpers/users_helper.rb
module UsersHelper

	def fullname(user)
		"#{user.firstname} #{user.lastname}"
	end

	def user_matches_balance(user)
		"win: #{@users_service.win_count(user)},
		lost: #{@users_service.lose_count(user)}"
	end
end

app/views/layouts/application.html.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'


  %body
    %nav.navbar.navbar-inverse
      .container-fluid
        .navbar-header
          %span.navbar-brand
            %b
              FOOSBALL TRACKER
        %div       
          %ul.nav.navbar-nav.navbar-left
            %li
              %a{:href => root_path}
                %span.glyphicon.glyphicon-list
                MATCHES  
            %li
              %a{:href => users_path}
                RANKING          

          %ul.nav.navbar-nav.navbar-right
            %li
              - if user_signed_in?
                %a{:href => user_path(current_user)}
                  %span.glyphicon.glyphicon-user
                  = current_user.firstname
                %li
                  %a{:href => edit_user_registration_path(current_user)}
                    edit profile
                %li
                  %a{"data-method" => "delete", :href => destroy_user_session_path, :rel => "nofollow"}
                    %span.glyphicon.glyphicon-log-out
                    Log-out
                %li.round-image-50=image_tag(current_user.avatar.url(:medium))
              - else
                %a{:href => new_user_session_path}
                  %span.glyphicon.glyphicon-log-in
                  Log-in
    .container
      .row
        .col-lg-12
          = yield

app/views/matches/_form.html.haml
= form_for @match do |f|
  .col-xs-12.col-sm-10.col-sm-offset-1
    - if @match.errors.any?
      .error_explanation
        %h4= "#{pluralize(@match.errors.count, "error")} prohibited this match from being saved:"
        %ul
          - @match.errors.full_messages.each do |msg|
            %li= msg
    %br

    .form-group
      = f.label :played_at, :class=>'singleline'
      = f.datetime_select :played_at, { :start_year => 2015, :end_year => Time.now.strftime("%Y").to_i }
    .form-group
      = f.label "win:"
      = f.select :winner_id, options_for_select(User.all.map{|u| ["#{u.firstname} #{u.lastname}", u.id]})
    %br
    .form-group
      = f.label "lose:"
      = f.select :loser_id, options_for_select(User.all.map{|u| ["#{u.firstname} #{u.lastname}", u.id]})
      / alternative
      / = f.collection_select :loser_id, User.all, :id, :firstname
    %br
    .form-group
      = f.label "by points:"
      = f.select :score, options_for_select((0..9).map {|i| [i,i]})
    %br
    = f.submit 'submit match', class: 'btn btn-default'
    %br
    %br

app/views/matches/index.html.haml
.container
  %hr
  .panel.panel-default
    .panel-body
      %div{:class => "col-md-3"}
        %b
          MATCHES LIST
      - if signed_in? && current_user.admin
        %div{:class => "col-md-9", :align => :right}
          = link_to 'New match', new_match_path, class: 'btn btn-default'
  .panel.panel-default
    .panel-body
      .table-responsible
        %table.table.table-hover
          %thead
            %tr
              %th win
              %th lose
              %th score
              %th date
              %th time
              %th additional info
          %tbody
            - @matches.reverse_each do |match|
              %tr
                %td                                 
                  = image_tag(winner_avatar_url(match, :medium))
                  = link_to winner_fullname(match), user_path(match.winner_id)
                %td
                  = image_tag(loser_avatar_url(match, :medium))
                  = link_to loser_fullname(match), user_path(match.loser_id)
                %td
                  = result(match)
                %td
                  = date(match)
                %td
                  = time(match)
                %td
                  - if match.surprise_victory?
                    .info
                      + 2 points for surprise victory!
                  - if match.score == 0
                    .info
                      + 1 point for perfect match!

  %br
  

app/views/matches/new.html.haml
.panel.panel-default
  .panel-body
    .row
      %div{:class => "col-md-3"}
        %h4{:align => :center}
          %b
            NEW MATCH
      %div{:class => "col-md-9", :align => :right}
        = link_to 'Cancel', root_path, class: 'btn btn-danger'
.panel.panel-default
  .panel-body
    = render 'form'

app/views/users/index.html.haml
.container
  %hr
  .row
    %div{:class => "col-md-3"}
      .panel.panel-default
        .panel-body
          %b
            BEST RATIOS
          %hr
          - @users_service.ranking(:ratio).each_with_index do |place, i|
            = "#{(i + 1).ordinalize} place (#{@users_service.ratio(place.first)})"
            %br
            - place.each do |user|
              = link_to fullname(user), user_path(user.id)
              %br
            %br
      .panel.panel-default
        .panel-body
          %b
            PERFECT PLAYERS
          %hr
          - @users_service.ranking(:perfect_count).each_with_index do |place, i|
            - break if @users_service.perfect_count(place.first) == 0
            = "#{(i + 1).ordinalize} place (#{@users_service.perfect_count(place.first)} perfect games)"
            %br
            - place.each do |user|
              = link_to fullname(user), user_path(user.id)
              %br
            %br
      .panel.panel-default
        .panel-body
          %b
            SURPRISES
          %hr
          - @users_service.ranking(:surprise_count).each_with_index do |place, i|
            - break if @users_service.surprise_count(place.first) == 0
            = "#{(i + 1).ordinalize} place (#{pluralize(@users_service.surprise_count(place.first), 'surprise win')})"
            %br
            - place.each do |user|
              = link_to fullname(user), user_path(user.id)
              %br
            %br


    %div{:class => "col-md-9"}
      .panel.panel-default
        .panel-body
          %b
            RANKING BY POINTS
      - @users_service.ranking(:points).each_with_index do |place, i|
        .panel.panel-default
          .panel-body
            %div{:class => "col-md-4"}
              %h3
                = "#{(i + 1).ordinalize} place"
                .small
                  = "score: #{pluralize(@users_service.points(place.first), 'point')}"
            %div{:class => "col-md-8"}
              %br
              - place.each do |user|
                %h4
                  = image_tag(user.avatar.url(:medium))
                  = link_to fullname(user), user_path(user.id)
                  .small
                    = "#{@users_service.win_count(user)} win, #{@users_service.lose_count(user)} lost"
                    - if @users_service.perfect_player?(user)
                      = ", #{pluralize(@users_service.perfect_count(user), 'perfect game')}"
                    - if @users_service.surprise_count(user) > 0
                      = ", #{pluralize(@users_service.surprise_count(user), 'surprise')}"
              %br
      %hr
  .row

app/views/users/show.html.haml
.container
  %div{:class => "col-md-3"}
    .panel.panel-default
      .panel-body
        %b
          PLAYER PROFILE
        %hr
        %div{:class => "col-md-8"}
          %h4
            = fullname(user)
            .small
              = user.email
        %div{:class => "col-md-4", :align => :right}
          %li.round-image-50=image_tag(user.avatar.url(:medium))
        %br
        %hr
        %div{:align => :right}
          %hr
          = user_matches_balance(user)
          %br
          = "ratio: #{@users_service.ratio(user)}"
          / %hr
          %br
          %br
          .small
            %table.table
              %thead
                %th subject
                %th score
              %tbody
                %tr
                  %td= pluralize(@users_service.win_count(user), 'win game')
                  %td= "+#{pluralize(@users_service.win_count(user), 'point')}"
                %tr
                  %td= pluralize(@users_service.lose_count(user), 'lost game')
                  %td= pluralize(@users_service.lose_count(user) * (-1), 'point')
                %tr
                  %td= pluralize(@users_service.perfect_count(user), 'perfect game')
                  %td= "+#{pluralize(@users_service.perfect_count(user), 'point')}"
                %tr
                  %td= pluralize(@users_service.surprise_count(user), 'surprise')
                  %td= "+#{pluralize(@users_service.surprise_count(user) * 2, 'point')}"
                %tr
                  %td
                    %b
                      SUM:
                  %td
                    = pluralize(@users_service.points(user), 'point')
          %br
          
          %br
          = "ranking position: #{@users_service.position_in_ranking(user, :points) + 1}"
  

  %div{:class => "col-md-9"}
    .panel.panel-default
      .panel-body
        %b
          RECENT MATCHES
    .panel.panel-default
      .panel-body
        .table-responsible
          %table.table.table-hover
            %thead
              %tr
                %th win
                %th lost
                %th score
                %th date
                %th time
                %th additional info
            %tbody
              - user.matches.reverse_each do |match|
                %tr
                  %td
                    = image_tag(winner_avatar_url(match, :thumb))
                    = link_to fullname(winner(match)), user_path(match.winner_id)
                  %td
                    = image_tag(loser_avatar_url(match, :thumb))
                    = link_to fullname(loser(match)), user_path(match.loser_id)
                  %td
                    = result(match)
                  %td
                    = date(match)
                  %td
                    = time(match)
                  %td
                    .info
                      - if match.surprise_victory?
                        = "+2p (surprise) "
                      - if match.score == 0
                        = "+1p (perfect)"
    %br